### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by osanwe** [mwcvitkovic/Deep_Learning_On_Code_With_A_Graph_Vocabulary--Code_Preprocessor#1]
Hello!

I have tried to reproduce your results and encountered some problems with Java 11.

Firstly, according to https://blog.codefx.org/java/java-11-migration-guide/#Removal-Of-Java-EE-Modules `javax.annotation` was removed. So this module should be imported manually in `javaparser-core`.

Secondly, by default `jrt:` protocol is used as default since Java 9. I know how to access Java modules (https://stackoverflow.com/a/46451977) but I could not find the way to fix the problem in this case.

I used the follow Dockerfile:
```
# Based on https://github.com/carlossg/docker-maven/blob/f581ea002e5d067deb6213c00a4d217297cad469/jdk-11/Dockerfile
FROM openjdk:11-jdk

ARG MAVEN_VERSION=3.5.4
ARG USER_HOME_DIR="/root"
ARG SHA=ce50b1c91364cb77efe3776f756a6d92b76d9038b0a0782f7d53acf1e997a14d
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

# Maven fails with 'Can't read cryptographic policy directory: unlimited'
# because it looks for $JAVA_HOME/conf/security/policy/unlimited but it is in
# /etc/java-9-openjdk/security/policy/unlimited
RUN ln -s /etc/java-11-openjdk /usr/lib/jvm/java-11-openjdk-$(dpkg --print-architecture)/conf

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

RUN mkdir /sources
WORKDIR /sources

CMD ["/bin/bash"]
```

When I have switched to Java 8, all worked without problem.

So I think it will be better to mention the Java version for usage, prepare a Dockerfile or update the code for Java 11.

**Comment by badalgeek** [comment]
It is specified in maven pom.xml:
https://github.com/mwcvitkovic/Open-Vocabulary-Learning-on-Source-Code-with-a-Graph-Structured-Cache--Code-Preprocessor/blob/master/pom.xml#L129
