### ISSUE TITLE
Augmented AST understanding

### ISSUE THREAD

**Issue by osanwe** [mwcvitkovic/Deep_Learning_On_Code_With_A_Graph_Vocabulary--Code_Preprocessor#2]
Hello!

I have studied `*.gml` code and some points are unclear for me.

Some nodes in graphs can contain the whole source code of module:
```
<node id="1">
    <data key="reference"></data>
    <data key="text">
        package org.slf4j.impl;

        import java.lang.reflect.Method;
        import org.slf4j.helpers.Util;

        public class VersionUtil {

            static final int MINIMAL_VERSION = 5;

            public static int getJavaMajorVersion() {
                String javaVersionString = Util.safeGetSystemProperty("java.version");
                return getJavaMajorVersion(javaVersionString);
            }

            static int getJavaMajorVersion(String versionString) {
                if (versionString == null)
                    return MINIMAL_VERSION;
                if (versionString.startsWith("1.")) {
                    return versionString.charAt(2) - '0';
                } else {
                    // we running under Java 9 or later
                    try {
                        Method versionMethod = Runtime.class.getMethod("version");
                        Object versionObj = versionMethod.invoke(null);
                        Method majorMethod = versionObj.getClass().getMethod("major");
                        Integer resultInteger = (Integer) majorMethod.invoke(versionObj);
                        return resultInteger.intValue();
                    } catch (Exception e) {
                        return MINIMAL_VERSION;
                    }
                }
            }
        }
    </data>
    <data key="type">CompilationUnit</data>
</node>
```

How do you process nodes like this?

**Comment by mwcvitkovic** [comment]
Hey @osanwe, thanks for your interest in our work!

The nodes in the Abstract Syntax Tree represent increasingly large segments of code as one goes from leaves to root.  The leaf nodes at the bottom of the tree represent small segments like individual words in the code.  The root node (or `Compilation Unit` node) represents an entire file.  [Wikipedia](https://en.wikipedia.org/wiki/Abstract_syntax_tree) gives a good explanation.

The `text` attribute of each node in the AST is just the entire segment of code that node represents.  So in the Compilation Unit node you copied above, the "text" attribute contains the entire text of a file.

Not sure what you mean by "how do you process", but we don't use the `text` attribute for anything except debugging/understanding.

**Comment by osanwe** [comment]
Hello @mwcvitkovic ,

I have another question about your augmented AST.

You listed all possible types of edges in AST (such as `AST`, `reversed_AST`, `LAST_READ`, etc) and did not mentioned types of nodes (such as `SimpleName`, `IfStmt`, `Parameter`, etc).
Is there a list of all possible values for this king of field, or it is better to parse the whole dataset for getting encountered values?

**Comment by mwcvitkovic** [comment]
Ah, good question.  On the python side, in this repo's sister repo [here](https://github.com/mwcvitkovic/Open-Vocabulary-Learning-on-Source-Code-with-a-Graph-Structured-Cache), we just assemble the list (in the all_node_types variable) while we're parsing the training data in the __init__ method of the various DataEncoders.  In this repo, all the possible node types for Java are fixed as part of the language standard and are built into the Javaparser library that we built on top of.

**Comment by mwcvitkovic** [comment]
Is the lack of a list of node types causing you trouble?

**Comment by osanwe** [comment]
Oh... It seems that JavaParser does not contain compiled list of node types, so yes, I also wrote the code for parsing a dataset for this kind of information. But I am not sure that all possible node types will be covered with this approach.

<br />

> Is the lack of a list of node types causing you trouble?

I do my own experiments based on your dataset and a list of node types will be useful.

<br />

Now the list looks like:
```
{'AnnotationDeclaration',
 'AnnotationMemberDeclaration',
 'ArrayAccessExpr',
 'ArrayCreationExpr',
 'ArrayCreationLevel',
 'ArrayInitializerExpr',
 'ArrayType',
 'AssertStmt',
 'AssignExpr',
 'BinaryExpr',
 'BlockStmt',
 'BooleanLiteralExpr',
 'BreakStmt',
 'CastExpr',
 'CatchClause',
 'CharLiteralExpr',
 'ClassExpr',
 'ClassOrInterfaceDeclaration',
 'ClassOrInterfaceType',
 'CompilationUnit',
 'ConditionalExpr',
 'ConstructorDeclaration',
 'ContinueStmt',
 'DoStmt',
 'DoubleLiteralExpr',
 'EmptyStmt',
 'EnclosedExpr',
 'EnumConstantDeclaration',
 'EnumDeclaration',
 'ExplicitConstructorInvocationStmt',
 'FieldAccessExpr',
 'FieldDeclaration',
 'ForStmt',
 'ForeachStmt',
 'IfStmt',
 'ImportDeclaration',
 'InitializerDeclaration',
 'InstanceOfExpr',
 'IntegerLiteralExpr',
 'LabeledStmt',
 'LambdaExpr',
 'LocalClassDeclarationStmt',
 'LongLiteralExpr',
 'MarkerAnnotationExpr',
 'MemberValuePair',
 'MethodCallExpr',
 'MethodDeclaration',
 'MethodReferenceExpr',
 'Name',
 'NameExpr',
 'NormalAnnotationExpr',
 'NullLiteralExpr',
 'ObjectCreationExpr',
 'PackageDeclaration',
 'Parameter',
 'PrimitiveType',
 'ReturnStmt',
 'SimpleName',
 'SingleMemberAnnotationExpr',
 'StringLiteralExpr',
 'SuperExpr',
 'SwitchEntryStmt',
 'SwitchStmt',
 'SynchronizedStmt',
 'ThisExpr',
 'ThrowStmt',
 'TryStmt',
 'TypeExpr',
 'TypeParameter',
 'UnaryExpr',
 'UnionType',
 'UnknownType',
 'VariableDeclarationExpr',
 'VariableDeclarator',
 'VoidType',
 'WhileStmt',
 'WildcardType'}
```
