### ISSUE TITLE
Error while processing the dataset.

### ISSUE THREAD

**Issue by hendersonweb** [mwcvitkovic/Deep_Learning_On_Code_With_A_Graph_Vocabulary--Code_Preprocessor#6]
Hello,  I was able to extract the repos successfully. But when I tried to execute processdataset.sh it gives the following error.

Error: Unable to access jarfile jar_path of javaparser-dloc-3.5.14-SNAPSHOT-jar-with-dependencies.jar

**Comment by mwcvitkovic** [comment]
Hi @st152840, thanks for your interest!  Do you have [Apache Maven](https://maven.apache.org/) installed and permissions for your user to run it?

**Comment by hendersonweb** [comment]
Hii @mwcvitkovic Thanks for your e-mail. I have done with mvn installed. I have found a solution to run without using shell file and just using java -jar "" "Input folder" "Output folder". It worked for this command directly

**Comment by SalaheddineBoukhoulda** [comment]
@st152840 Hello, i'm having the same error, would you please tell me how exactly you managed to execute it in details please because i'm no expert
