### ISSUE TITLE
Is it possible to extract only AST instead of augmented AST ?

### ISSUE THREAD

**Issue by laleye** [mwcvitkovic/Deep_Learning_On_Code_With_A_Graph_Vocabulary--Code_Preprocessor#7]
Hi, 
I would know if it is possible to extract the specific AST from a source file without the additional informations provided by the augmented AST ?

Thanks

**Comment by mwcvitkovic** [comment]
Hi @laleye, there's no functionality built for that I'm afraid.  You'd have to do it manually.

**Comment by laleye** [comment]
Manually like post-processing to extract AST from the result obtained?

**Comment by mwcvitkovic** [comment]
Yes, you'd just delete all the edge types that aren't AST edges.
